### ISSUE TITLE
ENG-252: Agree indicative content of the README.md file

### ISSUE THREAD

**Issue by stefaniuk** [nhs-england-tools/repository-template#1]
Our README.md file could contain sections as follows

- Project name
- Overview, a brief description of what the project is about and what it does
- Table of Contents
- Installation
- Usage 
- Architecture
    - Diagrams
    - Configuration
- Contributing
    - How to raise an issue or a feature request
    - References to the other documentation files
        - Versioning, Changelog, TODO list, ADR
        - Coding standards e.g. development & testing
- Contacts
- Licence

Some example

- [make-devops](https://github.com/make-ops-tools/make-devops/blob/main/build/automation/lib/project/template/README.md)
- [tis-microservice-template](https://github.com/Health-Education-England/tis-microservice-template/blob/main/README.md)
- [rap-package-template](https://github.com/NHSDigital/rap-package-template)
- [readme-templates](https://www.readme-templates.com/)

As part of this issue, we are not aiming to cover all the use cases and project types. This should be generic guidance on how to structure the entry point documentation file in a project.

**Comment by stefaniuk** [comment]
Reopening this issue as it was used for testing the flow along with an external PR.

**Comment by amaanibn-nasar1-nhs** [comment]
@stefaniuk I have a quick question on the C4 Model stuff. This seems a bit complicated to me. I haven't used it before and it feels a bit overkill for small projects. I've been documentation using the Draw.io integration extension on VSCode. This then allows you to edit diagrams within VSCode and directly embed the imaged into MD files. I hope that makes sense?

**Comment by stefaniuk** [comment]
@amaanibn-nasar1-nhs I can run a session on how this could work even for smaller projects. This is not contradictory to how you've been diagraming your work. The C4 model introduces consistency and clarity to the diagrams.
