### ISSUE TITLE
`.git/hooks/pre-commit` is far too slow

### ISSUE THREAD

**Issue by regularfry** [nhs-england-tools/repository-template#128]
### Is there an existing issue for this?

- [X] I have searched the existing Issues

### Current Behavior

`make config` installs a precommit hook to run a few tasks on commit.  It's far too slow to be useful.

```
$ time .git/hooks/pre-commit
...
...
.git/hooks/pre-commit  1.35s user 0.93s system 2% cpu 1:48.39 total
```

Most of that time was spent in the `scan-vulnerabilities.sh` script.

### Expected Behavior

`git commit` needs to be quick: if I'm not editing my commit message within a few seconds, I've probably forgotten the details of what I've just done.  It's an enforced context switch.  That prompts me to do commits less often, which means they're individually bigger.  That creates knock-on problems.

If we want to run `scan-vulnerabilities.sh` on the development machine, I suspect the right place to do it is on pre-push, rather than pre-commit.

### Steps To Reproduce

1. Check out the template
2. `make config` (doing whatever you need to get that working)
3. `time .git/hooks/pre-commit`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Sensitive Information Declaration

- [X] I confirm that neither PII/PID nor sensitive data are included in this form

**Comment by stefaniuk** [comment]
Grype [updates its database](https://github.com/anchore/grype#data-staleness) at the first run or every 5 days. The size is approximately 1GB.

I think this pre-hook should be removed. There isn't much benefit in running a potentially outdated CVE check locally, especially considering that the GitHub Action always performs a check against the latest version.
